apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ratings-robot-shop-vacx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ratings-robot-shop-vacx
    app.kubernetes.io/part-of: test-app
  name: ratings-robot-shop-vacx
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ratings-robot-shop-vacx
status:
  loadBalancer: {}
