apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: web-robot-shop-bvp8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: web-robot-shop-bvp8
    app.kubernetes.io/part-of: test-app
  name: web-robot-shop-bvp8
  namespace: srevivo-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: web-robot-shop-bvp8
status:
  loadBalancer: {}
