apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-java-springboot-basic-h5x8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-java-springboot-basic-h5x8
    app.kubernetes.io/part-of: test-app
  name: devfile-sample-java-springboot-basic-h5x8
  namespace: srevivo-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-sample-java-springboot-basic-h5x8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-sample-java-springboot-basic-h5x8
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:srevivo-tenant-devfile-sample-java-springboot-basic-h5x8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources:
          requests:
            cpu: 10m
            memory: 180Mi
status: {}
